### ISSUE TITLE
Request to revert OSS licenses of flomesh modules

### ISSUE THREAD

**Issue by UltraInstinct14** [flomesh-io/flb#5]
I am one of the maintainers of [loxilb](https://github.com/loxilb-io/loxilb). It has come to our notice that Flomesh repo https://github.com/flomesh-io/flb/tree/main/ebpf has changed the original copyright of [loxilb-ebpf](https://github.com/loxilb-io/loxilb-ebpf) modules.

If it is due to some mistake, we request to revert the original license. If not, we request to take down the repository at the earliest. @cybwan  @addozhang  @naqvis  @keveinliu @reaver-flomesh  @wanpf 

This is already raised [here](https://github.com/flomesh-io/fsm/issues/317) as well.

**Comment by caishu97** [comment]
Sorry for missing used the lox lib-ebpf module and license. We are no longer working on this project since last year, we so will just close this repo. Again, sorry for the inconvenience.
